### ISSUE TITLE
Update the Application Detail Page to include custom data information

### ISSUE THREAD

**Issue by thaneesh-babu** [HackGT/registration2#111]
We recently added a `customData` field to the application data model with [this](https://github.com/HackGT/api/commit/227bf83844e6c721991d43852c0d44035ca02071) commit aimed at including any additional information unique to a hexathon that isn't covered by the other fields. Right now, for hexathons like Horizons and Catalyst, a lot of the useful information is not displayed since they reside in the `customData` object. We'd like to also display relevant information from there in the Application Detail Page. Look at the json schema for the branches of these hexathons to see what data is being stored and display them accordingly.

**Comment by Roshan-D** [comment]
Also if you can try to update the application detail page to show only the fields that a specific hexathon has rather than just having it hardcoded in. For example, the application detail page is currently pretty useless for catalyst because we haven't added in any of those questions
